### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by AlfredMarcel** [yhgu2000/LogMeans#4]
试运行kmeans时出现（矩阵越界？）错误
![53fcd9005225b61aff087575614c342](https://github.com/yhgu2000/LogMeans/assets/49266277/9150146b-55ae-4b8d-9dc9-8846534c2730)

==================================================================
以下是launch脚本
![image](https://github.com/yhgu2000/LogMeans/assets/49266277/3cbd26fe-9431-4c62-872e-b2ff77d9c166)

==================================================================
以下是data_sample.json的内容：
{
    "dataset":{
        "rows": 10,
        "cols": 3,
        "data":[
            0.01,0.04,0.002,
            0.13784,0.1235,0.1155,
            -0.111,-0.1222,-0.1333,
            10.382,10.999,10.0101,
            10.12,10.188,10.132,
            10.1123,10.11432,10.114,
            100.234,100.367,100.3922,
            100.11,100.17,100.1222,
            100.113,100.11,100.1143,
            0.222,0.2122,0.2022
        ]
    }
}

**Comment by AlfredMarcel** [comment]
@yhgu2000 劳烦看一下问题所在TAT，代码在dt分支

**Comment by yhgu2000** [comment]
你知道在github里可以直接引用代码行吧：
https://github.com/yhgu2000/LogMeans/blob/215660d3d591bf19664f06ad92a23caa759bd3d6/lib/Lib/KMeans.cpp#L77

**Comment by yhgu2000** [comment]
https://github.com/yhgu2000/LogMeans/blob/215660d3d591bf19664f06ad92a23caa759bd3d6/lib/Lib/KMeans.cpp#L78

是不是因为你new_labels没有初始化。
另外你后面从数据集里取数据是按行的吗？我们是每列是一条数据：
https://github.com/yhgu2000/LogMeans/blob/449a1ca0b33a6e7f187b2fafefa1c25abefcf80a/lib/Lib/lib.hpp#L16

**Comment by yhgu2000** [comment]
我确实没发现什么问题，你确定是这一行出错的吗？

是哪个矩阵越界了？你把 `new_centers.row(new_labels(i))+=data.row(i);` 拆分成两行，就能看到了。

另外，虽然时间紧迫，这次就不要求了，但推荐一下我的编码规范：https://github.com/yhgu2000/LogMeans/blob/main/doc/coding_standards.md 😄

**Comment by AlfredMarcel** [comment]
已经解决
